name: Test
'on':
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    uses: escalate/github-actions-workflows/.github/workflows/test.yml@master

  goss:
    name: Goss
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Goss
        env:
          GH_REPO: goss-org/goss
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --pattern "*linux-amd64" --dir /tmp
          chmod +x /tmp/goss-linux-amd64
          mv /tmp/goss-linux-amd64 /usr/local/bin/goss

      - name: Run Goss
        run: |
          goss --vars vars.yaml validate
